### ISSUE TITLE
Trouble with Gradle

### ISSUE THREAD

**Issue by Radzhab** [jd-alexander/flender#2]
When i add you lib and build project - memory usage grows to up. In my project i have several libs

```
 compile 'com.android.support:design:22.2.0'
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.google.code.gson:gson:1.7.2'
    compile 'org.parceler:parceler-api:0.1.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.hotchemi:android-rate:0.4.3'
    compile 'com.hannesdorfmann:swipeback:1.0.0'
    compile 'com.makeramen:roundedimageview:2.1.0'
```

but when i add you lib its more time write - Building gradle....

**Comment by jd-alexander** [comment]
This is simply because the lib depends on the AspectJ compiler to compile all the classes you have annotated;therefore it's injecting the code at compile time.So this will indeed take a bit more time.
