### ISSUE TITLE
add a callback if Network isAvailable again?

### ISSUE THREAD

**Issue by rinav** [jd-alexander/flender#4]
In my current project I am displaying Snackbar when network is unavailable.

Can we somehow get a callback if the Network comes back again, so that I can remove Snackbar. I am not showing Snackbar for few seconds, but using Snackbar.LENGTH_INDEFINITE

**Comment by jd-alexander** [comment]
Based on the design of the library we don't currently support that feature. What you could do is simply use a broadcast receiver that listens for changes in connectivity and remove the snackbar afterwards.

**Comment by jd-alexander** [comment]
You would have to handle that scenario yourself; it's not within the scope of this library.
